//
//  Data.swift
//  PoemsID
//
//  Created by Rendi Wijiatmoko on 17/11/22.
//

import Foundation

let demoData: [RunningTradeModel] = [
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),

    RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
    RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
    RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
    RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
    RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
    
RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
    
RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),

    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    
RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
    
RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
    RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
    RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
    RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
    RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
    
RunningTradeModel(stock: "PBRX", name: "Pan Brothers Tbk.", price: 149, chg: "26.27", volume: 500, act: "BU", time: Date(),colorChg: .profit, stockType: [.M]),
RunningTradeModel(stock: "ZATA", name: "Bersama Zatta Jaya Tbk Pt", price: 264, chg: "-6.38", volume: 10, act: "BU", time: Date(),colorChg: .loss, stockType: [.S]),
RunningTradeModel(stock: "ASII", name: "Astra International Indonesia Tbk.", price: 6300, chg: "2.02", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.M, .L]),
RunningTradeModel(stock: "ADRO", name: "Adaro Energy Indonesia Tbk.", price: 3590, chg: "0.56", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "ICBP", name: "Indofood Cbp Sukses Makmur Tbk.", price: 9675, chg: "-1.02", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "PGAS", name: "Perusahaan Gas Negara Tbk.", price: 1800, chg: "-0.28", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "PTBA", name: "Bukit Asam Tbk.", price: 3550, chg: "1.43", volume: 200, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "BUKA", name: "Bukalapak.com Tbk.", price: 310, chg: "-0.64", volume: 13, act: "BU", time: Date(),colorChg: .loss, stockType: [.L,.M]),
RunningTradeModel(stock: "DIGI", name: "Arkadia Digital Media Tbk.", price: 50, chg: "-2", volume: 9, act: "BU", time: Date(), colorChg: .loss, stockType: [.S]),
RunningTradeModel(stock: "GOTO", name: "Goto Gojek Tokopedia Tbk.", price: 50, chg: "0", volume: 9, act: "BU", time: Date(), colorChg: .netral, stockType: [.L]),
RunningTradeModel(stock: "WEGE", name: "Wijaya Karya Bangunan Gedung T", price: 191, chg: "3.80", volume: 199, act: "BU", time: Date(), colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "PBRX", name: "Pan Brothers Tbk.", price: 149, chg: "26.27", volume: 500, act: "BU", time: Date(),colorChg: .profit, stockType: [.M]),
    RunningTradeModel(stock: "ZATA", name: "Bersama Zatta Jaya Tbk Pt", price: 264, chg: "-6.38", volume: 10, act: "BU", time: Date(),colorChg: .loss, stockType: [.S]),
    RunningTradeModel(stock: "ASII", name: "Astra International Indonesia Tbk.", price: 6300, chg: "2.02", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.M, .L]),
    RunningTradeModel(stock: "ADRO", name: "Adaro Energy Indonesia Tbk.", price: 3590, chg: "0.56", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "ICBP", name: "Indofood Cbp Sukses Makmur Tbk.", price: 9675, chg: "-1.02", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "PGAS", name: "Perusahaan Gas Negara Tbk.", price: 1800, chg: "-0.28", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "PTBA", name: "Bukit Asam Tbk.", price: 3550, chg: "1.43", volume: 200, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "BUKA", name: "Bukalapak.com Tbk.", price: 310, chg: "-0.64", volume: 13, act: "BU", time: Date(),colorChg: .loss, stockType: [.L,.M]),
    RunningTradeModel(stock: "DIGI", name: "Arkadia Digital Media Tbk.", price: 50, chg: "-2", volume: 9, act: "BU", time: Date(), colorChg: .loss, stockType: [.S]),
    RunningTradeModel(stock: "GOTO", name: "Goto Gojek Tokopedia Tbk.", price: 50, chg: "0", volume: 9, act: "BU", time: Date(), colorChg: .netral, stockType: [.L]),
    RunningTradeModel(stock: "WEGE", name: "Wijaya Karya Bangunan Gedung T", price: 191, chg: "3.80", volume: 199, act: "BU", time: Date(), colorChg: .profit, stockType: [.S,.M]),
    RunningTradeModel(stock: "PBRX", name: "Pan Brothers Tbk.", price: 149, chg: "26.27", volume: 500, act: "BU", time: Date(),colorChg: .profit, stockType: [.M]),
    RunningTradeModel(stock: "ZATA", name: "Bersama Zatta Jaya Tbk Pt", price: 264, chg: "-6.38", volume: 10, act: "BU", time: Date(),colorChg: .loss, stockType: [.S]),
    RunningTradeModel(stock: "ASII", name: "Astra International Indonesia Tbk.", price: 6300, chg: "2.02", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.M, .L]),
    RunningTradeModel(stock: "ADRO", name: "Adaro Energy Indonesia Tbk.", price: 3590, chg: "0.56", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "ICBP", name: "Indofood Cbp Sukses Makmur Tbk.", price: 9675, chg: "-1.02", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "PGAS", name: "Perusahaan Gas Negara Tbk.", price: 1800, chg: "-0.28", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "PTBA", name: "Bukit Asam Tbk.", price: 3550, chg: "1.43", volume: 200, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
    RunningTradeModel(stock: "BUKA", name: "Bukalapak.com Tbk.", price: 310, chg: "-0.64", volume: 13, act: "BU", time: Date(),colorChg: .loss, stockType: [.L,.M]),
    RunningTradeModel(stock: "DIGI", name: "Arkadia Digital Media Tbk.", price: 50, chg: "-2", volume: 9, act: "BU", time: Date(), colorChg: .loss, stockType: [.S]),
    RunningTradeModel(stock: "GOTO", name: "Goto Gojek Tokopedia Tbk.", price: 50, chg: "0", volume: 9, act: "BU", time: Date(), colorChg: .netral, stockType: [.L]),
    RunningTradeModel(stock: "WEGE", name: "Wijaya Karya Bangunan Gedung T", price: 191, chg: "3.80", volume: 199, act: "BU", time: Date(), colorChg: .profit, stockType: [.S,.M]),
    
]
let demoDataUniq: [RunningTradeModel] = [
    RunningTradeModel(stock: "ARTO", name: "Bank Jago Tbk", price: 6025, chg: "-3.60", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.L]),
RunningTradeModel(stock: "BBCA", name: "Bank Central Asia Tbk.", price: 8725, chg: "1.45", volume: 9, act: "BU", time: Date(),colorChg: .profit, stockType: [.M,.L]),
RunningTradeModel(stock: "BBRI", name: "Bank Rakyat Indonesia Tbk.", price: 4670, chg: "3.32", volume: 280, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M]),
RunningTradeModel(stock: "DSNG", name: "Dharma Satya Nusantara Tbk.", price: 590, chg: "-1.67", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
RunningTradeModel(stock: "TLKM", name: "Telkom Indonesia (Persero) Tbk.", price: 4040, chg: "-0.25", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "PWON", name: "Pakuwon Jati Tbk.", price: 442, chg: "-0.90", volume: 12, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M]),
RunningTradeModel(stock: "ITMG", name: "Indo Tambangraya Megah Tbk.", price: 38025, chg: "0.07", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M,.L]),
RunningTradeModel(stock: "PBRX", name: "Pan Brothers Tbk.", price: 149, chg: "26.27", volume: 500, act: "BU", time: Date(),colorChg: .profit, stockType: [.M]),
RunningTradeModel(stock: "ZATA", name: "Bersama Zatta Jaya Tbk Pt", price: 264, chg: "-6.38", volume: 10, act: "BU", time: Date(),colorChg: .loss, stockType: [.S]),
RunningTradeModel(stock: "ASII", name: "Astra International Indonesia Tbk.", price: 6300, chg: "2.02", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.M, .L]),
RunningTradeModel(stock: "ADRO", name: "Adaro Energy Indonesia Tbk.", price: 3590, chg: "0.56", volume: 434, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "ICBP", name: "Indofood Cbp Sukses Makmur Tbk.", price: 9675, chg: "-1.02", volume: 20, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "PGAS", name: "Perusahaan Gas Negara Tbk.", price: 1800, chg: "-0.28", volume: 434, act: "BU", time: Date(),colorChg: .loss, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "PTBA", name: "Bukit Asam Tbk.", price: 3550, chg: "1.43", volume: 200, act: "BU", time: Date(),colorChg: .profit, stockType: [.S,.M, .L]),
RunningTradeModel(stock: "BUKA", name: "Bukalapak.com Tbk.", price: 310, chg: "-0.64", volume: 13, act: "BU", time: Date(),colorChg: .loss, stockType: [.L,.M]),
RunningTradeModel(stock: "DIGI", name: "Arkadia Digital Media Tbk.", price: 50, chg: "-2", volume: 9, act: "BU", time: Date(), colorChg: .loss, stockType: [.S]),
RunningTradeModel(stock: "GOTO", name: "Goto Gojek Tokopedia Tbk.", price: 50, chg: "0", volume: 9, act: "BU", time: Date(), colorChg: .netral, stockType: [.L]),
RunningTradeModel(stock: "WEGE", name: "Wijaya Karya Bangunan Gedung T", price: 191, chg: "3.80", volume: 199, act: "BU", time: Date(), colorChg: .profit, stockType: [.S,.M]),
]
